yarnPath: .yarn/releases/yarn-4.2.2.cjs

changesetBaseRefs:
  - HEAD

nodeLinker: node-modules
npmPublishRegistry: 'https://registry.npmjs.org'

npmScopes:
  clownmeister:
    npmAlwaysAuth: true
    npmAuthToken: '${NODE_AUTH_TOKEN:secret}'
    npmPublishRegistry: 'https://registry.npmjs.org'
    npmRegistryServer: 'https://registry.npmjs.org'
