changesetBaseRefs:
  - HEAD

nodeLinker: node-modules
npmPublishRegistry: 'https://registry.npmjs.org'

npmScopes:
  clownmeister:
    npmAlwaysAuth: true
    npmAuthToken: '${NODE_AUTH_TOKEN}'
    npmPublishRegistry: 'https://registry.npmjs.org'
    npmRegistryServer: 'https://registry.npmjs.org'

yarnPath: .yarn/releases/yarn-4.1.1.cjs
