yarnPath: .yarn/releases/yarn-4.2.2.cjs

changesetBaseRefs:
  - HEAD

nodeLinker: node-modules
npmPublishRegistry: 'https://registry.npmjs.org'

npmRegistries:
  "https://registry.npmjs.org":
    npmAuthToken: '${NPM_TOKEN}'
    npmAlwaysAuth: true

npmScopes:
  clownmeister:
    npmAlwaysAuth: true
    npmRegistryServer: 'https://registry.npmjs.org'
