name: Main flow
#https://yarnpkg.com/configuration/yarnrc#npmAuthToken
#https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages
#https://github.com/actions/setup-node?tab=readme-ov-file
#https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#publish-to-npmjs-and-gpr-with-yarn
#https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data
#on:
#  release:
#    types: [created]
on:
  push:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Checkout source code
      - uses: actions/setup-node@v4
        name: Prepare Node Environment
        with:
          node-version: 22
          cache: yarn
          scope: clownmeister
      - name: Build and test
        run: |
          corepack enable
          yarn install --immutable
          yarn build
          yarn test

  publish-package:
    if: github.event_name == 'release' || github.event_name == 'workflow_dispatch'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        name: Checkout source code
      - uses: actions/setup-node@v4
        name: Prepare Node Environment
        with:
          node-version: 22
          cache: yarn
          scope: clownmeister
      - name: Setup .yarnrc.yml
        run: |
          yarn config set npmScopes.clownmeister.npmAuthToken $NPM_AUTH_TOKEN
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build and publish package
        run: |
          corepack enable
          yarn install --immutable
          yarn build
          yarn npm publish
